### ISSUE TITLE
Thoughts on the statsd-backend long term

### ISSUE THREAD

**Issue by nz** [dynmeth/statsd-backend#2]
As per the Readme:

> This backend is most probably redundant now since statsd now has a repeater backend which effectively serves the same purpose (relay stats to another server). Please let me know your thoughts on this.

For what it's worth, the statsd repeater implementation forwards every packet. I am interested in using a statsd package that sends over aggregates on every flushInterval, in order to spare a bit of load on our single central statsd server.

That seems to be a pretty worthwhile use case to me for the time being.

My $0.02! What are your thoughts?

**Comment by cjpartridgeb** [comment]
Most certainly, we initially assumed the repeater backend would be sending through aggregate data on the flushInterval but as you have noted it fowards every packet

We will update the README soon :)

Cheers,

Chris

**Comment by nz** [comment]
Perfect!
